baseURL = "https://blog.jcapucho.ml/"
languageCode = "en-us"
title = "Capucho's blog"
paginate = 10
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "Capucho's blog"
description = "This is my personal blog where I post about my work"
keywords = [ "Blog" ]
author = "João Capucho"
images = [ "/banner.jpg" ]
DateFormat = "2 January, 2006"
defaultTheme = "auto"
ShowReadingTime = true
ShowCodeCopyButtons = true
disableSpecial1stPost = false
disableScrollToTop = true
comments = true
hidemeta = false
hideSummary = false
showtoc = true
tocopen = false

  [params.assets]
  favicon = "/favicon.ico"
  favicon16x16 = "/favicon-16x16.png"
  favicon32x32 = "/favicon-32x32.png"
  apple_touch_icon = "/apple-touch-icon.png"

  [params.label]
  text = "Home"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.homeInfoParams]
  Title = "Welcome to my personal blog"
  Content = """
  Hi there, I'm a student that likes programming and to write about it.

  I focus mainly on programming languages development and graphics
  related topics but also do some web development from time to time.
  """

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/JCapucho"

  [[params.socialIcons]]
  name = "RsS"
  url = "index.xml"

  [[menu.main]]
  identifier = "Search"
  name = "Search"
  url = "/search/"
  weight = 5

  [[menu.main]]
  identifier = "Tags"
  name = "Tags"
  url = "/tags/"
  weight = 10

  [[menu.main]]
  identifier = "Archive"
  name = "Archive"
  url = "/archives/"
  weight = 20

  [outputs]
  home = ["HTML", "RSS", "JSON"]
